[project]
name = "anime-recommender-system"
version = "0.1.0"
requires-python = ">=3.10,<3.12"

dependencies = [
    "chromadb==0.5.5",
    "langchain==0.2.16",
    "langchain-community==0.2.16",
    "langchain-groq==0.1.9",
    "langchain-huggingface==0.0.3",
    "pandas==2.2.2",
    "python-dotenv==1.0.1",
    "streamlit==1.37.1",
    "sentence-transformers==2.7.0",
    "transformers==4.41.1",
    "torch>=2.2.0"
]

[tool.setuptools]
packages = ["config", "utils", "pipeline", "src"]
