#

import os
import logging
from datetime import datetime


# setup folder for logs
LOG_DIR = "logs"

# create logs directory if it doesn't exist
# it will be used to store log files generated by the application
#It will create in root directory of the project
# if exist_ok=True -> it will not create the directory if it already exists, preventing errors if the directory is already present. If the directory does not exist, it will be created.
os.makedirs(LOG_DIR, exist_ok=True)

# create file name which will be used to store logs
# the file name is generated using the current date and time, ensuring that each log file is unique and can be easily identified based on when it was created.
LOG_FILE = os.path.join(LOG_DIR, f"log_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.log")

# configure logging settings
# logging.basicConfig() is used to configure the logging system. It sets the log level to INFO, which means that all log messages with a severity level of INFO or higher will be recorded.
# INFO-> it is message level. It is used for normal messsages.
# Warning-> it is message level. It used for warning messages.
# ERROR-> it is message level. It is used for error messages.
# The log messages will be written to the file specified by LOG_FILE, and the format of the log messages will include the timestamp, log level, and the actual log message. This setup allows for organized and timestamped logging of events in the application, making it easier to track and debug issues
logging.basicConfig(
    level=logging.INFO,
    filename=LOG_FILE,
    format="%(asctime)s - %(levelname)s - %(message)s",
)

# to use logger in other modules, we can create a logger  function that returns a logger instance. 
# This allows us to easily log messages from different parts of the application while maintaining a consistent logging format and configuration.
# getLogger -> attaching logger to basicConfig.
def get_logger(name):
    logger = logging.getLogger(name) 
    logger.setLevel(logging.INFO)
    return logger